export const categoriesData = [
  {
    id: '1',
    name: 'School',
    iconName: 'ios-school-outline',
    percent: 75,
    amount: 375,
  },
  {
    id: '2',
    name: 'Bills',
    iconName: 'ios-paper-outline',
    percent: 50,
    amount: 250,
  },
  {
    id: '3',
    name: 'Eating Out',
    iconName: 'ios-restaurant-outline',
    amount: 175,
    percent: 25,
  },
  {
    id: '4',
    name: 'Entertainment',
    iconName: 'ios-game-controller-b-outline',
    percent: 23,
    amount: 145,
  },
  {
    id: '5',
    name: 'Shopping',
    iconName: 'ios-shirt-outline',
    percent: 12,
    amount: 110,
  },
  {
    id: '6',
    name: 'General',
    iconName: 'ios-cash-outline',
    percent: 10,
    amount: 100,
  },
  {
    id: '7',
    name: 'Holiday',
    iconName: 'plane',
    percent: 8,
    amount: 100,
  },
  {
    id: '8',
    name: 'Health',
    iconName: 'heart',
    percent: 5,
    amount: 80,
  },
  {
    id: '9',
    name: 'Clothes',
    iconName: 'ios-basket',
    percent: 5,
    amount: 50,
  },
  {
    id: '10',
    name: 'Transport',
    iconName: 'ios-car-outline',
    percent: 5,
    amount: 50,
  },
];
