export const expensesData = [
  {
    id: 0,
    title: 'Taxi to office',
    date: '2018-08-05',
    amount: -25,
    type: 'Credit card',
    category: 'Transport',
    categoryIcon: 'ios-car-outline',
  },
  {
    id: 1,
    title: 'Launch with Alex',
    date: '2018-08-05',
    amount: -30.8,
    type: 'Credit card',
    category: 'Eating Out',
    categoryIcon: 'ios-restaurant-outline',
  },
  {
    id: 2,
    title: 'Pay check',
    date: '2018-08-05',
    amount: 3000,
    type: 'Bank transfert',
    category: 'Income',
    categoryIcon: 'ios-swap',
  },
  {
    id: 3,
    title: 'Coffee with Jane',
    date: '2018-08-04',
    amount: -10,
    type: 'Cash',
    category: 'Eating Out',
    categoryIcon: 'ios-restaurant-outline',
  },
  {
    id: 4,
    title: 'Electricity bill',
    date: '2018-08-04',
    amount: -50,
    type: 'Credit Card',
    category: 'Bills',
    categoryIcon: 'ios-paper-outline',
  },
  {
    id: 6,
    title: 'Cinema with children',
    date: '2018-08-04',
    amount: -50,
    type: 'Credit Card',
    category: 'Entertainment',
    categoryIcon: 'ios-game-controller-b-outline',
  },
  {
    id: 7,
    title: 'Dinner with family',
    date: '2018-08-04',
    amount: -80,
    type: 'Cash',
    category: 'Eating Out',
    categoryIcon: 'ios-restaurant-outline',
  },
  {
    id: 8,
    title: 'shirt and jean for Adam',
    date: '2018-08-03',
    amount: -120,
    type: 'Credit Card',
    category: 'Car',
    categoryIcon: 'ios-shirt-outline',
  },
  {
    id: 9,
    title: 'Weekly shopping',
    date: '2018-08-03',
    amount: -150.5,
    type: 'Credit Card',
    category: 'Shopping',
    categoryIcon: 'ios-basket',
  },
  {
    id: 10,
    title: 'Weekly shopping',
    date: '2018-08-03',
    amount: -150.5,
    type: 'Credit Card',
    category: 'Shopping',
    categoryIcon: 'ios-basket',
  },
  {
    id: 11,
    title: 'Stuff from Amazon',
    date: '2018-08-03',
    amount: -25.5,
    type: 'Credit Card',
    category: 'Shopping',
    categoryIcon: 'ios-basket',
  },
  {
    id: 12,
    title: 'Parking',
    date: '2018-08-03',
    amount: -5.5,
    type: 'Cash',
    category: 'Transport',
    categoryIcon: 'ios-car-outline',
  },
];
